glaucous:
- 0
- 1

leaf_lobed:
- 0
- 1

leaf_type:
- broadleaf
- needle

leaf_compoundness:
- simple
- compound
- simple or appearing so

leaf_phenology:
- evergreen
- deciduous

life_history:
- annual
- perennial
- biennial
- ephemeral
- annual/biennial

lignotuber:
- 0
- 1

lineage:
- dicotyledon
- monocotyledon

nitrogen_fixing:
- 0
- 1

photosynthetic_pathway:
- C3
- C4

plant_growth_form:
- herb
- subshrub
- shrub
- shrub tree
- tree
- climber
- parasite
- epiphyte
- graminoid
- aquatic
- fern
- palm

serotiny:
- 0
- 1

succulent:
- 0
- 1

woodiness:
- herbaceous
- woody
- semi- woody
