glaucous:
- 0
- 1

leaf_lobed:
- 0
- 1

leaf_type:
- broadleaf
- needle
- article

leaf_compoundness:
- simple
- compound
- simple or appearing so
- leafless

leaf_phenology:
- evergreen
- deciduous
- semi-deciduous
- facultative

life_history:
- annual
- biennial
- annual biennial
- perennial
- annual perennial
- biennial perennial
- annual biennial perennial
- ephemeral
- short-lived
- indefinite
- long-lived
- perennial assumed

lignotuber:
- 0
- 1

lineage:
- dicotyledon
- monocotyledon

nitrogen_fixing:
- 0
- 1

photosynthetic_pathway:
- C3
- C4

plant_growth_form:
- herb
- herb shrub
- subshrub
- shrub
- shrub tree
- tree
- climber
- parasite
- epiphyte
- graminoid
- aquatic
- fern
- palm

serotiny:
- 0
- 1

succulent:
- 0
- 1

woodiness:
- herbaceous
- woody
- semi-woody
